version: '3.4'

services:
  nodebackend:
    image: nodebackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
